#!/usr/bin/env bash
# ============================================================================
# AIR-GAP CONFIG — tune llama.cpp to THIS host, exactly. No fantasy sizes.
# Reads host-capabilities.json (probes if missing) → writes llama-host.env:
# the GGUF tier that actually FITS the measured RAM, llama-server flags, and
# the LOCAL_LLM_* exports the sovereign gateway reads to arm its offline slot.
#
# Tier law (Q4_K_M ≈ 0.6 GB per B params, plus ~0.5–0.8 GB runtime overhead):
#   avail < 3.5 GB  → 3B  instruct (ctx 4096)
#   avail < 6.5 GB  → 7B  coder   (ctx 8192)
#   avail < 14 GB   → 14B coder
#   else            → 32B coder  (the manifest's dream tier — real hosts only)
# A GPU host sets GPU_LAYERS=999 (offload everything) automatically.
# ============================================================================
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "$HERE/host-capabilities.json" ]] || bash "$HERE/probe-host.sh" > /dev/null

jval() { sed -n "s/.*\"$1\": \([^,}]*\).*/\1/p" "$HERE/host-capabilities.json" | head -1; }
cores=$(jval cpu_cores)
avail=$(jval mem_available_mb)
disk=$(jval disk_free_mb)
gpu=$(jval gpu)

name=""; repo=""; model_file=""; ctx=4096; layers=0
if (( avail < 3500 )); then
  name="qwen2.5-3b-instruct-q4-k-m"; repo="Qwen/Qwen2.5-3B-Instruct-GGUF"; model_file="qwen2.5-3b-instruct-q4_k_m.gguf"; ctx=4096
elif (( avail < 6500 )); then
  name="qwen2.5-coder-7b-instruct-q4-k-m"; repo="Qwen/Qwen2.5-Coder-7B-Instruct-GGUF"; model_file="qwen2.5-coder-7b-instruct-q4_k_m.gguf"; ctx=8192
elif (( avail < 14000 )); then
  name="qwen2.5-coder-14b-instruct-q4-k-m"; repo="Qwen/Qwen2.5-Coder-14B-Instruct-GGUF"; model_file="qwen2.5-coder-14b-instruct-q4_k_m.gguf"; ctx=8192
else
  name="qwen2.5-coder-32b-instruct-q4-k-m"; repo="Qwen/Qwen2.5-Coder-32B-Instruct-GGUF"; model_file="qwen2.5-coder-32b-instruct-q4_k_m.gguf"; ctx=8192
fi
[[ "$gpu" == "true" ]] && layers=999 # offload everything
threads=$(( cores > 0 ? cores : 2 ))

cat > "$HERE/llama-host.env" <<EOF
# generated by llama-host-config.sh from host-capabilities.json — never hand-fake
AIRGAP_MODEL_NAME=$name
AIRGAP_MODEL_REPO=$repo
AIRGAP_MODEL_FILE=$model_file
AIRGAP_THREADS=$threads
AIRGAP_CTX=$ctx
AIRGAP_GPU_LAYERS=$layers
# exports the sovereign gateway reads (air-gap slot arms when these exist):
LOCAL_LLM_URL=http://127.0.0.1:8080/v1
LOCAL_LLM_MODELS=$name
EOF

echo "[airgap] tier=$name threads=$threads ctx=$ctx gpu_layers=$layers (avail=${avail}MB disk=${disk}MB cores=$cores gpu=$gpu)"
echo "[airgap] wrote $HERE/llama-host.env"
